### ISSUE TITLE
Unable to decrypt output even though Input file exists

### ISSUE THREAD

**Issue by prajwaljpj** [marcobellaccini/pyAesCrypt#26]
I'm facing an issue decrypting the file after Pyinstaller.
The file `/x/y/z/abc.pt.aes` Exists!
```python
decrypting /x/y/z/abc.pt.aes to /tmp/_MEIyWW0kG/abc.pt
Traceback (most recent call last):
  File "pyAesCrypt/crypto.py", line 258, in decryptFile
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIyWW0kG/abc.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyAesCrypt/crypto.py", line 271, in decryptFile
OSError: Unable to write output file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "serve.py", line 63, in <module>
  File "backend_code.py", line 50, in __init__
  File "backend_code.py", line 123, in decrypt_files
  File "decrypt.py", line 36, in decryptfile
  File "pyAesCrypt/crypto.py", line 279, in decryptFile
OSError: File "/x/y/z/abc.pt.aes" was not found.

```

Any suggestions?

**Comment by marcobellaccini** [comment]
Hi,
the error messages were misleading.
This has been fixed in https://github.com/marcobellaccini/pyAesCrypt/commit/ca6bd344e0449929814f9bdfc897c2e315bf2a00

Thank you for pointing out

Cheers

Marco
