### ISSUE TITLE
shows import error for email.utils

### ISSUE THREAD

**Issue by Sanju-S** [marcobellaccini/pyAesCrypt#4]
I followed everything clearly on the python interpreter but it shows import error as 
`
>>> import pyAesCrypt as pc
>>> pc.encryptFile("/Users/Sanju/Documents/views.py", "/Users/Sanju/Documents/views.aes", "password", 64 * 1024)
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    pc.encryptFile("/Users/Sanju/Documents/views.py", "/Users/Sanju/Documents/views.aes", "password", 64 * 1024)
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyAesCrypt\crypto.py", line 97, in encryptFile
    key = stretch(passw, iv1)
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyAesCrypt\crypto.py", line 65, in stretch
    passHash = hashes.Hash(hashes.SHA256(), backend=default_backend())
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cryptography\x509\general_name.py", line 10, in <module>
    from email.utils import parseaddr
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\email.py", line 1, in <module>
    import smtplib
  File "C:\Users\Sanju\AppData\Local\Programs\Python\Python36-32\lib\smtplib.py", line 47, in <module>
    import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package`

**Comment by marcobellaccini** [comment]
Hi,
I've just tested your code snippet in a similar environment (Python 3.6.6 x86-64 on Windows 10 1803) and it works fine.
Some people complained about this error on Stackoverflow:
https://stackoverflow.com/questions/33313858/importerror-no-module-named-email-mime-email-is-not-a-package

I'm closing the issue because the problem seems unrelated to pyAesCrypt.

Thank you for using pyAesCrypt.

Cheers

Marco
