### ISSUE TITLE
Password Issue Encryptfile()

### ISSUE THREAD

**Issue by LpCodes** [marcobellaccini/pyAesCrypt#41]
I have a directory with 4 text files now when I run try encrypt file function I am getting this below error

```
Traceback (most recent call last):
  File "c:\Users\Documents\user\1\myfile.py", line 4, in <module>
    encrypt_dir(r'D:\New folder')
  File "C:\Python38\lib\site-packages\pycryptobox\encryption.py", line 49, in encrypt_dir
    chck = pyAesCrypt.encryptFile(
  File "C:\Python38\lib\site-packages\pyAesCrypt\crypto.py", line 95, in encryptFile
    encryptStream(fIn, fOut, passw, bufferSize)
  File "C:\Python38\lib\site-packages\pyAesCrypt\crypto.py", line 118, in encryptStream
    if len(passw) > maxPassLen:
TypeError: object of type 'NoneType' has no len()
```

Can you kindly check & let me if there is any limit on using the password length ,currently I am storing pass in a env file MY_PASSWORD=mysecretpassword & loading inside main file  load_dotenv , password = os.getnev('MY_PASSWORD")

The same code works on one system but on other its fails

**Comment by LpCodes** [comment]
closing as it was password issue which was not loading while packaging
